#!/bin/bash

# build storybook distros
cd packages/good-design
yarn --check-cache

if ! yarn build-storybook; then
  exit 1
fi

cd ../sdk-v2
yarn --check-cache
export STORYBOOK_BASEPATH=/sdk/

if ! yarn build-storybook -- --preview-url=/sdk/iframe.html; then
  exit 1
fi

cd ../../

# pre-create output folders
mkdir -p dist/storybook/sdk

# copy bundles. UI goes to the root, sdk-v2 will be at /sdk
cp -R packages/good-design/storybook-static/* dist/storybook
cp -R packages/sdk-v2/storybook-static/* dist/storybook/sdk
