#!/bin/bash

rm -rf node_modules
rm -rf packages/good-design/node_modules
rm -rf packages/sdk-v2/node_modules
rm -rf packages/good-design/storybook-static
rm -rf packages/sdk-v2/storybook-static
rm -rf dist/storybook
rm -f yarn.lock

export YARN_FLAGS=
export

# build storybook distros
cd packages/good-design
touch yarn.lock
yarn

if ! yarn build-storybook; then
  exit 1
fi

cd ../sdk-v2
touch yarn.lock
yarn
export STORYBOOK_BASEPATH=/sdk/

if ! yarn build-storybook -- --preview-url=/sdk/iframe.html; then
  exit 1
fi

cd ../../

# pre-create output folders
mkdir -p dist/storybook/sdk

# copy bundles. UI goes to the root, sdk-v2 will be at /sdk
cp -R packages/good-design/storybook-static/* dist/storybook
cp -R packages/sdk-v2/storybook-static/* dist/storybook/sdk
